function [ScatteringMatrix] = ASOW_ScatteringMatrix (Freq, CouplCoeff_k1, Radius, Alpha, Alpha_2)
    % Returns the Transfer Function of Scheuer's SOW when given the
    % parameters
    EffRefrIndex = 2.362;
    SpeedLight = 3e8; % m/s
    Trans_k1 = sqrt(1-CouplCoeff_k1^2);
    % Freq is in THz
    pA = (pi^2*EffRefrIndex*Radius*1e12)/SpeedLight;
    pB = (4*pi*EffRefrIndex*Radius*Alpha*1e12)/SpeedLight;
    pD = (4*pi*EffRefrIndex*Radius*Alpha_2*1e12)/SpeedLight;
    
    PhaseSectionA = Freq * pA;
    PhaseSectionB = Freq * pB;
    PhaseSectionD = Freq * pD;
    
    
    ScatteringMatrix =[ - (exp(PhaseSectionA*1i)*exp(PhaseSectionB*1i)*exp(PhaseSectionD*1i))/(exp(PhaseSectionD*1i)*Trans_k1^3 - exp(PhaseSectionD*1i)*Trans_k1) - (Trans_k1*exp(PhaseSectionA*1i)*exp(PhaseSectionB*1i)*exp(PhaseSectionD*1i))/(- exp(PhaseSectionD*1i)*Trans_k1^2 + exp(PhaseSectionD*1i)),                                                                                                                                                       0,                                                                                                                                            0,  -(CouplCoeff_k1^2*exp(PhaseSectionB*1i))/(- exp(PhaseSectionD*1i)*Trans_k1^2 + exp(PhaseSectionD*1i)),  -(CouplCoeff_k1^2*exp(PhaseSectionB*1i))/(exp(PhaseSectionD*1i)*Trans_k1^3 - exp(PhaseSectionD*1i)*Trans_k1),                                                   0;
                                                                                                                                                                                                                                                                                    0,                                                     -(exp(-PhaseSectionA*1i)*exp(-PhaseSectionA*2i)*exp(-PhaseSectionD*1i)*1i)/(CouplCoeff_k1*Trans_k1),                                                       (exp(-PhaseSectionA*2i)*exp(PhaseSectionB*1i)*exp(-PhaseSectionD*1i)*1i)/CouplCoeff_k1,                                                                                                      0,                                                                                                             0, -(CouplCoeff_k1*exp(-PhaseSectionA*2i)*1i)/Trans_k1;
                                                                                                                                                                                                                                                                                     0,                                                                                                                                                       0,                                                                                                                                            0,                                             (CouplCoeff_k1*exp(PhaseSectionA*2i))/(Trans_k1^2*1i - 1i),                                          -(CouplCoeff_k1*Trans_k1*exp(PhaseSectionA*2i))/(Trans_k1^2*1i - 1i),                                                   0;
                                                                                                                                                                                                                                                                                    0,                                                                                                                            -(Trans_k1*1i)/CouplCoeff_k1,                                                                               (exp(PhaseSectionA*1i)*exp(PhaseSectionB*1i)*1i)/CouplCoeff_k1,                                                                                                      0,                                                                                                             0,                                                   0;
                       (Trans_k1*1i)/CouplCoeff_k1 + (exp(PhaseSectionD*1i)*1i)/(CouplCoeff_k1*(exp(PhaseSectionD*1i)*Trans_k1^3 - exp(PhaseSectionD*1i)*Trans_k1)) + (Trans_k1*exp(PhaseSectionD*1i)*1i)/(CouplCoeff_k1*(- exp(PhaseSectionD*1i)*Trans_k1^2 + exp(PhaseSectionD*1i))),                                                                                                                                                       0,                                                                                                                                            0, (CouplCoeff_k1*exp(-PhaseSectionA*1i)*1i)/(- exp(PhaseSectionD*1i)*Trans_k1^2 + exp(PhaseSectionD*1i)), (CouplCoeff_k1*exp(-PhaseSectionA*1i)*1i)/(exp(PhaseSectionD*1i)*Trans_k1^3 - exp(PhaseSectionD*1i)*Trans_k1),                                                   0;
                                                                                                                                                                                                                                                                                     0, - (Trans_k1*exp(-PhaseSectionA*1i)*exp(-PhaseSectionD*1i))/CouplCoeff_k1^2 + (exp(-PhaseSectionA*1i)*exp(-PhaseSectionD*1i))/(CouplCoeff_k1^2*Trans_k1), - (exp(PhaseSectionB*1i)*exp(-PhaseSectionD*1i))/CouplCoeff_k1^2 + (Trans_k1^2*exp(PhaseSectionB*1i)*exp(-PhaseSectionD*1i))/CouplCoeff_k1^2,                                                                                                      0,                                                                                                             0,                                          1/Trans_k1];
                                                                                                                                                                                                                                                                                 
end
